apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-maria-db
  namespace: default
spec:
  serviceName: {{ .Release.Name }}-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-maria-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-maria-db
    spec:
      containers:
        - image: {{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          name: {{ .Release.Name }}-maria-db
          resources: {}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: userpassword
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: db
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: {{ .Values.mariadb.volumes.name }}
              mountPath: {{ .Values.mariadb.volumes.mountPath }}
 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{ .Values.mariadb.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.mariadb.PVC.name }}
 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.mariadb.PV.name }}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.mariadb.PV.reclaimPolicy }}
  storageClassName: standard
  capacity:
    storage: {{ .Values.mariadb.PV.size }}
  hostPath:
    path: {{ .Values.mariadb.PV.path }}/{{ .Release.Name }}
 
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.mariadb.PVC.name }}
  namespace: default
spec:
  volumeName: {{ .Release.Name }}-{{ .Values.mariadb.PV.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.PVC.size }}
 
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.mariadb.service.name }}
spec:
  ports:
    - port: {{ .Values.mariadb.service.port }}
  selector:
    app: {{ .Release.Name }}-maria-db
