#Mettre (true ou false)
ingress:
  enable: true

server:
  replicaCount: 2

  securityContext:
    runAsUser: 82
    runAsGroup: 82

  liveness:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 5

  image:
    repository:  codebuds/micro-symfony-webserver
    pullPolicy: IfNotPresent
    tag: 0.1.3

  volumes:
    name: logs
    mountPath: /srv/app/shared-logs

  PV:
    name: pv-deno-server
    size: 3Gi
    path: /data/deno-server/
    reclaimPolicy: Retain    

  PVC:
    name: logs
    size: 1Gi

  service:
    name: service-deno-webserver
    type: ClusterIP
    ports:
      protocol: TCP
      port: 8000
      targetPort: 8000

mariadb:
  database: logs

  root_password: asecret
  
  readiness:
    initialDelaySeconds: 20
    periodSeconds: 5
    failureThreshold: 5

  user:
    login: user
    password: password

  image:
    repository: mariadb
    pullPolicy: Always
    tag: 10.7

  volumes:
    name: maria-db
    mountPath: /var/lib/mysql

  PV:
    name: pv-maria-db
    size: 10Gi
    path: /data/maria-db/
    reclaimPolicy: Retain

  PVC:
    name: maria-db
    size: 1Gi

  service:
    name: maria-db
    port: 3306